import { useAppDispatch } from "@/app_redux/hooks";
import Layout from "@/components/layout/Layout";
import CategoryBlock from "@/components/products/categories/CategoryBlock";
import { setCategoryProductList, setCategorySizeOptions, setCategoryVolumeOptions } from "@/features/categoryDetailsSlice";
import { ProductListInterface } from "@/interfaces/ProductInterfaces";
import axios from "axios";
import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import Head from "next/head";

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
    const options = {
        headers: {
            withCredentials: true,
        }
    }
    const id = context.params?.id;
    const url = process.env.NEXT_PUBLIC_BASE_URL_SERVER + "/api/product/getProductsByCategoryId/" + id;
    const response = await axios.get(url, options);
    const productList: ProductListInterface[] = response.data.data;

    return {
        props: {
            productList,
        }
    }
}

const sizeOptions = ['S', 'M', 'XL', 'XXL'];
const volumeOptions = ['100 ml', '200 ml'];

const ProductDetailsPage = ({ productList }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

    const dispatch = useAppDispatch();
    dispatch(setCategoryProductList(productList));
    dispatch(setCategorySizeOptions(sizeOptions));
    dispatch(setCategoryVolumeOptions(volumeOptions));
    
    return (
        <>
            <Head>
                <title>DogHouse</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <CategoryBlock />
            </Layout>
        </>
    )
}

export default ProductDetailsPage;