import BillingBlock from "@/components/checkout/billing/BillingBlock";
import CheckoutLayout from "@/components/layout/CheckoutLayout";
import Head from "next/head";

const BillingPage = () => {
    return (
        <>
            <Head>
                <title>DogHouse | Billing Details</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CheckoutLayout>
                <BillingBlock />
            </CheckoutLayout>
        </>
    )
}

export default BillingPage;