import ConfirmBlock from "@/components/checkout/confirm/ConfirmBlock";
import CheckoutLayout from "@/components/layout/CheckoutLayout";
import Head from "next/head";

const ConfirmPage = () => {
    return (
        <>
            <Head>
                <title>DogHouse | Confirm Order</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CheckoutLayout>
                <ConfirmBlock />
            </CheckoutLayout>
        </>
    )
}

export default ConfirmPage;