import MainBannerBlock from '@/components/homepage/banner/MainBannerBlock'
import ProductCategories from '@/components/homepage/categories/ProductCategories'
import NewProducts from '@/components/homepage/newProducts/NewProducts'
import Layout from '@/components/layout/Layout'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>DogHouse</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainBannerBlock />
        <NewProducts />
        <ProductCategories />
      </Layout>
    </>
  )
}
