import PaymentBlock from "@/components/checkout/payment/PaymentBlock";
import CheckoutLayout from "@/components/layout/CheckoutLayout";
import Head from "next/head";
import CreditCardImage from "../../public/creditcard.png";
import CashOnDeliveryImage from "../../public/cashondelivery.png";
import { PaymentOptionInterface } from "@/interfaces/checkout/PaymentInterface";

const paymentOptions: PaymentOptionInterface[] = [
    {
        id: 2,
        name: "Credit Card",
        image: CreditCardImage
    },
    {
        id: 3,
        name: "Cash On Delivery",
        image: CashOnDeliveryImage
    },
]

const ShippingPage = () => {

    return (
        <>
            <Head>
                <title>DogHouse | Payment Details</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CheckoutLayout>
                <PaymentBlock paymentOptions={paymentOptions}/>
            </CheckoutLayout>
        </>
    )
}

export default ShippingPage;