import PaymentBlock from "@/components/checkout/payment/PaymentBlock";
import CheckoutLayout from "@/components/layout/CheckoutLayout";
import Head from "next/head";
import axios from "axios";
import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
    const options = {
        headers: {
            withCredentials: true,
        }
    }
    const url = `${process.env.NEXT_PUBLIC_BASE_URL_SERVER}/api/order/getPaymentOptions`;
    const response = await axios.get(url, options);
    const paymentOptions = response.data.data;
    
    return {
        props: {
            paymentOptions,
        }
    }
}

const ShippingPage = ({ paymentOptions }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

    return (
        <>
            <Head>
                <title>DogHouse | Payment Details</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CheckoutLayout>
                <PaymentBlock paymentOptions={paymentOptions}/>
            </CheckoutLayout>
        </>
    )
}

export default ShippingPage;