import ShippingBlock from "@/components/checkout/shipping/ShippingBlock";
import CheckoutLayout from "@/components/layout/CheckoutLayout";
import Head from "next/head";

const ShippingPage = () => {
    return (
        <>
            <Head>
                <title>DogHouse | Shipping Details</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CheckoutLayout>
                <ShippingBlock />
            </CheckoutLayout>
        </>
    )
}

export default ShippingPage;