import Layout from "@/components/layout/Layout";
import ProductDetailsBlock from "@/components/products/productDetails/ProductDetailsBlock";
import { ProductDataInterface } from "@/interfaces/ProductInterfaces";
import Head from "next/head";
import { useAppDispatch } from "@/app_redux/hooks";
import { setProductData, setSizeOptions, setVolumeOptions } from "@/features/productDetailsSlice";
import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import axios from "axios";

export const getServerSideProps = async (context: GetServerSidePropsContext) => {
    const productName = context.query.productName;
    const id = context.query.id;
    const options = {
        params: { productName, id },
        headers: {
            withCredentials: true,
        }
    }
    const url = `${process.env.NEXT_PUBLIC_BASE_URL_SERVER}/api/Product/GetProductDataByName`;
    const response = await axios.get(url, options);
    const productData: ProductDataInterface = response.data.data.productData;
    const sizeOptions = response.data.data.sizeOptions;
    const volumeOptions = response.data.data.volumeOptions;

    return {
        props: {
            productData,
            sizeOptions,
            volumeOptions
        }
    }
  }

const ProductDetailsPage = ({ productData, sizeOptions, volumeOptions }: InferGetServerSidePropsType<typeof getServerSideProps>) => {

    const dispatch = useAppDispatch();

    dispatch(setProductData(productData));
    dispatch(setSizeOptions(sizeOptions));
    dispatch(setVolumeOptions(volumeOptions));

    return (
        <>
            <Head>
                <title>DogHouse</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <ProductDetailsBlock />
            </Layout>
        </>
    )
}

export default ProductDetailsPage;